name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.12.1
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  provider: ^6.1.5
  video_player: ^2.10.0
  wakelock_plus: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
